Моделирование предметной области, ассоциации моделей
RubyRockstar/Rails pull request #5
Opened 2021-08-03 16:01 UTC by RubyRockstar

2021-08-04 09:16 UTC, VidgarVii requested changes

2021-08-04 09:16 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2021-08-04 09:16 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Смотри пример тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2021-08-04 09:16 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :category
Соблюдай очередность.
Принято сначала писать belongs_to далее ниже has_

Пример оформления модели
https://github.com/rubocop-hq/rails-style-guide#macro-style-methods

2021-08-04 09:16 UTC, VidgarVii commented on app/models/user.rb
> +      .joins("JOIN results ON tests.id = results.test_id")
тут тоже надо отрефачить как метод titles_by_category

2021-08-04 09:16 UTC, VidgarVii commented on db/seeds.rb
> +  { title: 'UFC Heavyweight', level: 2, category_id: categories[2].id, author_id: users[0].id }
теперь, благодаря ассоциациям, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `category: categories[0]`, `author: users[0]` и т.п. (без `_id` , `.id`)

2021-08-04 09:16 UTC, VidgarVii commented on db/seeds.rb
> +results = Result.create! ([
переменная results не используется. Лучше её не объявлять

2021-08-04 11:21 UTC, RubyRockstar commented on app/models/category.rb
> +  has_many :tests
![Снимок экрана от 2021-08-04 14-00-57](https://user-images.githubusercontent.com/58150711/128172374-72235268-babe-4735-9395-3372ed7c6b2d.png)

2021-08-04 11:54 UTC, VidgarVii requested changes

2021-08-04 11:54 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :author, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
не согласуется со схемой

2021-08-04 11:54 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests, dependet: :destroy
не согласуется со схемой

2021-08-05 07:49 UTC, VidgarVii requested changes

2021-08-05 07:49 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests, dependent: :destroy
категории не исправил по схеме

2021-08-05 07:49 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :tests, through: :results? dependent: :nullify
тут ошибки

2021-08-05 07:49 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :tests, through: :results? dependent: :nullify
для ассоциации has_many through достаточно 1 раз указать dependent

2021-08-05 07:49 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :author, class_name: 'Test', foreign_key: 'author_id'
нет dependent

2021-08-12 07:38 UTC, merged